results_dir: 2020-08-29_512_pts_rec_ids_012_interrupted #2020-08-29_64_pts_rec_ids_012_scale_35_offset_-1_5
plot_type: ['all'] #['rhos_meas_over_epochs']
cell_id: '2020-08-29_1' 
rec_ids: [0,1,2] 
start_n_scan: 100
num_datapoints_per_scanfield: 512 #64
nseg: 4
selected_type: 'train' # 'val' or 'test' or 'train'
