defaults:
  - _self_

# This can be list of types of figures. leave empyt if non desired
debugging_figs: ['recording_comps_and_rois']

# cell info
cell_id: "2020-08-29_1"

# training specifics
lr: 0.005
momentum: 0.5
iterations: 200
reduce_lr_every: 800
reduce_lr_by: 5 #10.0
beta: 0.99
soma_radius: 7.5

# offset and scale
output_scale: 35.0
output_offset: -1.5
# scale_tranable: true
# offset_trainable: true

weight_init: 0.1 #"random"
batchsize:  2
rec_ids: [0,1,2] #[1,2,3,4,5,6,7] #[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
num_datapoints_per_scanfield: 64 #1024
val_frac:  0.25
test_num: 8 #128
vis: true
seed_weights: 10
seed_membrane_conds: 0
seed_tf_dataloader: 0
seed_tf_train_loop: 0
seed_ruler: 0
eval_every_nth_batch: 100
start_n_scan: 100
nseg: 4
reuse_avg_recordings: false




hydra:
  run:
    dir: /gpfs01/euler/User/ssuhai/GitRepos/jaxley_rgc/deistler_our_data_and_morph/results/train_runs/${now:%Y_%m_%d}__${now:%H_%M_%S}/0 # added base dir 
  sweep:
    dir: /gpfs01/euler/User/ssuhai/GitRepos/jaxley_rgc/deistler_our_data_and_morph/results/train_runs/${now:%Y_%m_%d}__${now:%H_%M_%S}_m
    subdir: ${hydra.job.num}
